version: "3.5"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bookCatalog, artifactory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - admin-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - admin-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: " 	laiba@yahoo.com"
      PGADMIN_DEFAULT_PASSWORD: "pass123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - admin-network

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/jenkins_home
    networks:
      - admin-network

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.71.11
    container_name: artifactory
    ports:
      - 8099:8081 # for router communication
    #            - 8081:8081 # for artifactory communication
    depends_on:
      - postgresql
    links:
      - postgresql
    volumes:
      - /data/artifactory:/var/opt/jfrog/artifactory
    environment:
      - DB_TYPE=postgresql
      # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      # Add extra Java options by uncommenting the following line
      #- EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      - admin-network

networks:
  books-project:
    driver: bridge