pipeline {
    agent any

    tools {
        maven "3.9.6"
    }

    stages {
        // checkout de master, based on jenkins configuration
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // builds the java project
        stage('Build') {
            steps {
                sh "ssh -V"
                sh "mvn -version"
                sh "mvn clean install"
            }
        }

        // runs the unit tests
        stage('Unit Test') {
            steps {
                sh 'mvnw -Dtest="com.critical.catalogservice/controller/*" test'
                sh 'mvnw -Dtest="com.critical.catalogservice/data/*" test'
                sh 'mvnw -Dtest="com.critical.catalogservice/service/*" test'
                sh 'mvnw -Dtest="*ApplicationTests" test'
            }

            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }

        // Run integration tests
        stage('Integration Test') {
            steps {
                sh './mvnw -Dtest="com.critical.catalogservice/integration/*" test'
            }

            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}