pipeline {
    agent any

    tools {
        maven "3.9.6"
    }

    stages {
        // checkout de master, based on jenkins configuration
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // builds the java project
        stage('Build') {
            steps {
                sh "mvn clean install -DskipTests"
            }
        }

        // runs the unit tests
        stage('Unit Test') {
            steps {
                sh 'mvn -Dtest="com.critical.catalogservice/controller/**" test'
                sh 'mvn -Dtest="com.critical.catalogservice/data/**" test'
                sh 'mvn -Dtest="com.critical.catalogservice/service/**" test'
                sh 'mvn -Dtest="*ApplicationTests" test'
            }

            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }

        // Run integration tests
        stage('Integration Test') {
            steps {
                sh './mvn -Dtest="com.critical.catalogservice/integration/**" test'
            }

            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}